services:
  camping:
    image: cmuname/sw-docker:camping
    container_name: camping-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/sw/work/logs:/app/logs
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:10.0.2.2"

  board:
    image: cmuname/sw-docker:board
    container_name: board-container
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /home/sw/work/logs:/app/logs
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:10.0.2.2"

  store:
    image: cmuname/sw-docker:store
    container_name: store-container
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /home/sw/work/logs:/app/logs
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:10.0.2.2"

  auth:
    image: cmuname/sw-docker:auth
    container_name: auth-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
        - /home/sw/work/logs:/app/logs
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:10.0.2.2"

  gateway:
    image: cmuname/sw-docker:gateway
    container_name: gateway-container
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

networks:
  backend:
    driver: bridge