server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: camping_public
          uri: http://camping-container:8080/
          predicates:
            - Path=/campings/**
        - id: camping_user
          uri: http://camping-container:8080/
          predicates:
            - Path=/camping/bookmarks/**, /camping/reviews/**
          filters:
            - JwtAuthenticationFilter
        - id: camping_admin
          uri: http://camping-container:8080/
          predicates:
            - Path=/camping/admin/**
          filters:
            - JwtAuthenticationFilter
            - JwtAuthorizationFilter

        - id: board_public
          uri: http://board-container:8080/
          predicates:
            - Path=/board/posts/**
            - Method=GET
        - id: board_post_user
          uri: http://board-container:8080/
          predicates:
            - Path=/board/posts/**
            - Method=POST,DELETE
          filters:
            - JwtAuthenticationFilter
        - id: board_user
          uri: http://board-container:8080/
          predicates:
            - Path=/board/comments/**, /board/messages/**
          filters:
            - JwtAuthenticationFilter
        - id: board_admin
          uri: http://board-container:8080/
          predicates:
            - Path=/board/admin/**
          filters:
            - JwtAuthenticationFilter
            - JwtAuthorizationFilter

        - id: store_public
          uri: http://store-container:8080/
          predicates:
            - Path=/store/products/**
        - id: store_user
          uri: http://store-container:8080/
          predicates:
            - Path=/store/bookmark/**, /store/reviews/**, /store/address/**, /store/carts/**, /store/orders/**
          filters:
            - JwtAuthenticationFilter
        - id: store_admin
          uri: http://store-container:8080/
          predicates:
            - Path=/store/category/admin/**, /store/admin/**
          filters:
            - JwtAuthenticationFilter
            - JwtAuthorizationFilter

        - id: auth
          uri: http://auth-container:8080/
          predicates:
          - Path=/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://host.docker.internal:5173"
              - "http://localhost:5173" 
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "OPTIONS"
              - "PATCH"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST, DELETE, PATCH

jwt:
  secret: 5asf46g8asg56hesh8j65j4g23agw874rq564asg56h48ry47sd65g4ag8q